### ISSUE TITLE
Can't install base_headers_webkit

### ISSUE THREAD

**Issue by mamolas** [OCA/webkit-tools#12]
I'm trying to install invoice_webkit but its dependence  base_headers_webkit isn't on my local module list, I've extracted **unported** folder contents into my addons folder, also extracted individually base_headers_webkit folder and report_webkit_chapter_server folder but after update the list, they still don't appear on frontend to install, any clue?

**Comment by guewen** [comment]
When the modules are located in `__unported__`, they need to be migrated to the new odoo version, so they don't necessarily work yet.

The migration process for a module is to:
- Move the module in the root of the directory
- Set `installable` to `True` in `__openerp__.py`
- Migrate the code and XML to the new version (new API, ...)
- Remove deprecated code or XML
- Eventually add tests
- Submit a PR on the main branch

Hope this will help

**Comment by mamolas** [comment]
I'm still on OpenErp7, setting installable to true was enough, but now I can't print invoices from accounting>>Customer Invoices is there some guide? Thanks

**Comment by yvaucher** [comment]
If you are on Odoo 7.0 please take the module from 7.0 branch:

https://github.com/OCA/webkit-tools/tree/7.0

For installation, you might want to refer to:
https://www.odoo.com/forum/help-1/question/how-to-configure-webkit-for-v7-4724

**Comment by gurneyalex** [comment]
@damodaranudas if you used git clone to get the source, be sure to switch to the correct branch with `git checkout 7.0` (8.0 is the default)
