### ISSUE TITLE
resize of barcode image in webkit report

### ISSUE THREAD

**Issue by mfzoutsource** [OCA/webkit-tools#27]
Hi @pedrobaeza ,

I'm working on how to print barcode image into webkit report by using this in openerp7 :- 
${helper.barcode(o.name, "Code128")}

So how can I resize that image such as add width or height value within that line such as:
${helper.barcode(o.name, "Code128", png, width="30%")}
by using this funtion:-
barcode(value, code='Code128', drawOpts=None, htmlAttrs=None).

Is there any syntax or specific parameter's name that I can use to resize that image?

Thank you.

**Comment by pedrobaeza** [comment]
Why are you making a question here? This is for reporting issues or wishlist for this project. You should use any of the usual channels for this (Odoo forum specially). Anyway, I don't know now what you want to do (if in a QWeb repor or what), so please specify when reporting in the other place.
